# Generated by Django 4.2.10 on 2024-02-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('post', models.CharField(max_length=50, verbose_name='Post at work')),
                ('info', models.CharField(max_length=250, verbose_name='employee information')),
                ('image', models.ImageField(unique=True, upload_to='staff_images', verbose_name='image')),
                ('inst', models.URLField(blank=True, verbose_name='instagram')),
                ('twitter', models.URLField(blank=True, verbose_name='twitter')),
                ('facebook', models.URLField(blank=True, verbose_name='facebook')),
            ],
        ),
    ]
