# Generated by Django 4.2.10 on 2024-02-25 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_staff'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staff',
            table='staff cards',
        ),
    ]
