# Generated by Django 4.2.10 on 2024-02-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_of_interest', models.CharField(max_length=200, verbose_name='place of interest')),
                ('location', models.CharField(max_length=200, verbose_name='location')),
                ('image', models.ImageField(upload_to='place_images', verbose_name='image of the place')),
            ],
            options={
                'db_table': 'pictures on the main page',
            },
        ),
    ]
