# Generated by Django 4.2.10 on 2024-02-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pic_slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider_images')),
            ],
            options={
                'verbose_name': 'images for slider',
                'db_table': 'images for slider',
            },
        ),
        migrations.AlterModelOptions(
            name='main',
            options={'verbose_name': 'posts on the main page'},
        ),
    ]
